# Generated by Django 4.2.14 on 2024-07-18 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("new_App", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactmessage",
            name="user",
        ),
    ]
