# Generated by Django 4.2.14 on 2025-08-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("new_App", "0002_event_eventimage_leadership_newslettersubscriber_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventimage",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
