# Generated by Django 4.2.14 on 2024-07-19 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("new_App", "0002_remove_contactmessage_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Programs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("p_name", models.CharField(max_length=100)),
                ("p_description", models.CharField(max_length=200)),
                ("p_price", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
