# Generated by Django 4.2.13 on 2025-09-16 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_App', '0002_alter_eventimage_image_alter_leadership_l_imagename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='l_imagename',
            field=models.ImageField(upload_to='leadership/'),
        ),
    ]
