# Generated by Django 4.2.13 on 2026-08-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_App', '0004_contactmessage_subject_contactmessage_other_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=100)),
                ('e_description', models.CharField(max_length=1000)),
                ('e_imagename', models.ImageField(upload_to='executives/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which this profile appears')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Executive',
                'verbose_name_plural': 'Executives',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoogleForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('programs_booking', 'Programs Page - School Presentation Booking Form'), ('executive_applications', 'Get Involved Page - Executive Applications Form')], max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('form_url', models.URLField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Google Form',
                'verbose_name_plural': 'Google Forms',
            },
        ),
    ]
