# Generated by Django 4.2.13 on 2026-08-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_App', '0005_executive_googleform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, choices=[('school_partnership', 'School Partnership / Presentation'), ('volunteer', 'Volunteer / Get Involved'), ('executive_team', 'FGEN Executive Team'), ('student_questions', 'Student Questions'), ('parent_guardian', 'Parent / Guardian Inquiry'), ('general_inquiry', 'General Inquiry'), ('collaboration_partnership', 'Collaboration / Partnership'), ('media_press', 'Media / Press Inquiry'), ('feedback_suggestions', 'Feedback / Suggestions'), ('others', 'Other')], default='', max_length=50),
        ),
    ]
