# Generated by Django 4.2.13 on 2024-07-20 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_App', '0007_pdfdocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdfdocument',
            options={'verbose_name': 'Newsletter Document', 'verbose_name_plural': 'Newsletter Documents'},
        ),
    ]
