# Generated by Django 4.2.13 on 2024-07-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_App', '0009_userpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpayment',
            name='stripe_charge_id',
            field=models.CharField(default='', max_length=500),
        ),
    ]
