# Generated by Django 4.2.13 on 2024-07-28 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_App', '0012_webdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayment',
            name='donation_type',
            field=models.CharField(default='regular', max_length=50),
        ),
    ]
