# Generated by Django 4.2.14 on 2024-07-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("new_App", "0013_userpayment_donation_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpayment",
            name="app_user",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="userpayment",
            name="stripe_charge_id",
            field=models.CharField(default="", max_length=500, unique=True),
        ),
    ]
