# Generated by Django 4.2.14 on 2024-07-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("new_App", "0014_alter_userpayment_app_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadership",
            name="l_description",
            field=models.CharField(max_length=500),
        ),
    ]
