# Generated by Django 4.2.14 on 2024-07-31 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("new_App", "0016_alter_leadership_l_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadership",
            name="l_imagename",
            field=models.ImageField(upload_to=""),
        ),
    ]
