# Generated by Django 4.2.14 on 2024-07-31 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("new_App", "0017_alter_leadership_l_imagename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadership",
            name="l_imagename",
            field=models.ImageField(upload_to="static/assets/images/"),
        ),
    ]
