# Generated by Django 4.2.14 on 2024-07-31 15:42

from django.db import migrations, models
import new_App.models


class Migration(migrations.Migration):

    dependencies = [
        ("new_App", "0018_alter_leadership_l_imagename"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("t_name", models.CharField(max_length=100)),
                ("t_description", models.CharField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="leadership",
            name="l_imagename",
            field=models.ImageField(upload_to=new_App.models.upload_to),
        ),
    ]
