# Generated by Django 4.2.14 on 2024-08-14 01:11

from django.db import migrations, models
import django.db.models.deletion
import new_App.models


class Migration(migrations.Migration):

    dependencies = [
        ("new_App", "0019_testimonials_alter_leadership_l_imagename"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to=new_App.models.upload_to)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="new_App.event",
                    ),
                ),
            ],
        ),
    ]
