# Generated by Django 4.2.14 on 2024-08-14 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("new_App", "0020_eventimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventimage",
            name="event",
        ),
    ]
